version: '3.8'

services:
  database_service:
    image: mysql
    container_name: db
    ports:
      - 3310:3306
    volumes:
      - C:\Users\Admin\Desktop\unknow-pj\db\data:/var/lib/mysql
      - C:\Users\Admin\Desktop\unknow-pj\db\conf:/etc/mysql/conf.d
    environment:
      - MYSQL_USER=nhanpq
      - MYSQL_PASSWORD=abc123
      - MYSQL_ROOT_PASSWORD=abc123
      - MYSQL_DATABASE=moviereview
    networks:
      - mynetwork
    
networks:
  mynetwork:
    name: mynetwork-name